[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci --omit=dev']

[phases.build]
cmds = ['npx playwright install chromium', 'npx playwright install-deps chromium']

[start]
cmd = 'node build/index.js'